apiVersion: v2
name: cloudstack-csi
description: A Helm chart for CloudStack CSI driver
type: application
version: 2.2.1
appVersion: 0.8.1
sources:
  - https://github.com/Leaseweb/cloudstack-csi-driver
keywords:
  - csi
  - cloudStack
maintainers:
  - name: hrak
  - name: FarnazBGH
  - name: lanord
